/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Version": "版本",
    "-====}=+ WELCOME TO FARA! +={====-": "-====}=+ 欢迎来到 FARA! +={====-",
    "Preparing the grandest of adventures...": "",
    "MAP": "地图",
    ",  and a": ", 和一个",
    ", a": "， 一个",
    ", and": "， 和",
    ", and go to them with": "，然后去他们那里",
    ", or": "， 或者",
    ", press": "， 按",
    ", remove them with": ", 删除它们",
    ", type": "， 类型",
    "! CAPSLOCK ON !": "！大写锁定！",
    ". FARA also submits error reports": ". FARA 还提交错误报告",
    ". It is": ".这是",
    ". It is imbued with arcane energy.  It is about your size.": ".它充满了奥术能量。它和你的大小差不多。",
    ". They start their journey with": ".他们开始他们的旅程",
    ". To disable sharing your adventures with our highly supportive community, type": ".要禁用与我们高度支持的社区分享您的冒险经历，请输入",
    "...A": "...一个",
    "' or": "' 或者",
    "' to create the listed item.": "' 以创建列出的物品。",
    "'. Type '": "'。类型 '",
    "'Name'": "'名称'",
    "'Number'": "'数字'",
    "(gray)": "（灰色）",
    "(Soldier)": "（士兵）",
    ")": ")",
    "[ 1 ]": "[ 1 ]",
    "[ a ]": "[ a ]",
    "[ Arrow Keys ]": "[ 方向键 ]",
    "[ e ]": "[e]",
    "[ Esc ]": "[ Esc键 ]",
    "[ r ]": "[r]",
    "[ shift + p ]": "[ shift + p ]",
    "[ t ]": "[t]",
    "[ Tab ]": "[ Tab ]",
    "[Click here or type": "[点击这里或输入",
    "/changelog": "/更改日志",
    "/clearlocalwaypoint": "/clearlocalwaypoint",
    "/clearwaypoint": "/clearwaypoint",
    "/close": "/关闭",
    "/craft": "/工艺",
    "/goto": "/前往",
    "/help": "/帮助",
    "/inspect": "/检查",
    "/makespell": "/制造法术",
    "/random": "/随机",
    "/recipes": "/配方",
    "/setlocalwaypoint": "/setlocalwaypoint",
    "/setname": "/setname",
    "/setwaypoint": "/setwaypoint",
    "/stopreports": "/停止报告",
    "/stopsharing": "/停止分享",
    "/trackwaypoint": "/trackwaypoint",
    "0 days, 0 hours": "0天0小时",
    "0 days, 1 hour": "0天1小时",
    "0.0.16.5d": "0.0.16.5d",
    "0.0.16.5d Browser": "0.0.16.5d 浏览器",
    "1 Spell Slot": "1 个法术位",
    "3. Cancel": "3. 取消",
    "A glowing, viscous liquid oozes from this ghostly apparition's eyes and mouth.": "一种发光的粘稠液体从这个幽灵的眼睛和嘴里渗出。",
    "about nine steps to the south. A glowing, viscous liquid oozes from this ghostly apparition's eyes and mouth.  It is  holding an": "向南大约九步。一种发光的粘稠液体从这个幽灵的眼睛和嘴里渗出。它拿着一个",
    "Above Average": "高于平均水平",
    "Above Average Health": "高于平均水平",
    "Above Average Resilience": "高于平均弹性",
    "ACCESSORY": "配饰",
    "Actions & Gestures": "动作和手势",
    "Adamantine Scythe": "金刚镰刀",
    "Adventurer": "冒险家",
    "Air Attunement": "空气调谐",
    "All Rights Reserved": "版权所有",
    "An": "一个",
    "AN ENCOUNTER!": "一次邂逅！",
    "and": "和",
    "Approach Shrouded Figure": "接近笼罩图",
    "Approach Tattered Note": "接近破烂的笔记",
    "Approach Wooden Breastpl...": "接近木制胸罩",
    "Arcane": "奥术",
    "Artifacts Recovered": "恢复的文物",
    "Ash Tree": "白蜡树",
    "Astral Blessing": "星体祝福",
    "Astral Conversion": "星体转换",
    "Average": "平均",
    "B!": "乙！",
    "Below Average": "低于平均水平",
    "Below Average Insight": "低于平均水平的洞察力",
    "BODY": "身体",
    "Burlap Satchel": "粗麻布挎包",
    "Campfire": "营火",
    "Campfire (Fixed)": "营火（固定）",
    "Cancel": "取消",
    "Charm Rating": "魅力评级",
    "Clear waypoints you no longer need by typing": "通过键入清除不再需要的航点",
    "click": "点击",
    "click anywhere in the middle of the screen": "单击屏幕中间的任意位置",
    "click anywhere in the middle of the screen and select 'Get Random Adventurer'": "单击屏幕中间的任意位置并选择“获取随机冒险者”",
    "click outside of this window": "在此窗口外单击",
    "command. The number in": "命令。中的号码",
    "Compare Items": "比较物品",
    "Condition:": "生命值）状况：",
    "Conditions:": "条件：",
    "Consumes a single Key Fragment to permanently increase an ability score of your choosing": "消耗一个关键碎片来永久增加你选择的能力值",
    "Consumes ALL collected Key Fragments to completely restore the caster and damage nearby enemies": "消耗所有收集的钥匙碎片以完全恢复施法者并伤害附近的敌人",
    "Current Score": "当前分数",
    "Damage Reduction": "减少伤害",
    "Darkness Attunement": "黑暗调和",
    "Dash": "短跑",
    "Dash to Shrouded Figure": "破折号到笼罩图",
    "Dash to Tattered Note": "破破烂烂的纸条",
    "Dash to Wooden Breastpl...": "Dash to 木制胸罩",
    "Days Survived": "生存天数",
    "Desired Name": "所需名称",
    "Destealth": "暗杀",
    "Details:": "详情：",
    "dies by bleeding.": "死于流血。",
    "Distance Traveled": "行驶距离",
    "DM2": "DM2",
    "Dodge": "躲闪",
    "Dogged March": "顽强的三月",
    "DOGGED MARCH": "顽强的三月",
    "drag": "拖",
    "drops a": "滴一个",
    "Dungeons Cleared": "地下城通关",
    "Earth Attunement": "地球调谐",
    "Element:": "元素：",
    "elements around the interface to perform most actions. Type": "界面周围的元素以执行大多数操作。类型",
    "Engaging it in combat would surely be your undoing.": "将它投入战斗肯定会是你的毁灭。",
    "Entrance: N": "入口：N",
    "Exit Area": "出口区",
    "FACTIONS": "派系",
    "FARA is a game about exploration and discovery. It's light on visuals, so you are encouraged to imagine what's described in the coolest way possible.": "FARA 是一款关于探索和发现的游戏。它在视觉上很轻松，因此鼓励您以最酷的方式想象所描述的内容。",
    "FARA shares your accomplishments to a": "FARA 将您的成就分享给",
    "FEET": "脚",
    "Finesse Rating": "技巧等级",
    "Fire Attunement": "火调",
    "Friends Made": "结交朋友",
    "Gain increased damage resistance as health decreases": "随着生命值的降低，获得更高的伤害抗性",
    "GAME LOCKED - New Instance Detected": "游戏锁定 - 检测到新实例",
    "Get Random Adventurer": "获得随机冒险者",
    "Get Random Name": "获取随机名称",
    "ghostly figure": "鬼影",
    "Good": "好的",
    "Good luck out there. -": "祝你好运。 -",
    "Good Strength": "强度好",
    "HANDS": "手",
    "HEAD": "头",
    "Health": "生命值",
    "Healthy": "生命值",
    "help me fix bugs. To disable this, type": "帮我修复错误。要禁用此功能，请键入",
    "High Score": "高分",
    "HOLDING": "当前",
    "Hostile": "敌对的",
    "indicates how many of a given material you have on you or within reach.": "表示您拥有或触手可及的给定材料的数量。",
    "Insight Rating": "洞察力评级",
    "Inspect": "检查",
    "Inspect Shrouded Figure": "检查遮蔽图",
    "Inspect Tattered Note": "检查破烂的纸条",
    "Inspect Wooden Breastpl...": "检查木制胸...",
    "INVENTORY": "存货",
    "is 14 kilometers to the north": "向北 14 公里",
    "is bleeding heavily!": "正在大量流血！",
    "It is  8 steps out of your attack range.": "它在你的攻击范围之外 8 步。",
    "item name": "物品名",
    "ITEMS": "物品",
    "Items & Equipment": "物品和设备",
    "Items Discovered": "发现的物品",
    "Javan Softfist the Soldier": "士兵爪哇软拳",
    "Key Fragment": "关键片段",
    "Key Fragment": "关键片段",
    "Key Fragments": "关键片段",
    "Known Spells": "已知法术",
    "Learned Spells (0/1)": "学习法术 (0/1)",
    "Light Attunement": "光调",
    "Lives Taken": "夺走生命",
    "Look Around": "环视四周",
    "looming over an injured adventurer.": "逼近受伤的冒险者。",
    "MAIN MENU": "主菜单",
    "MAINHAND": "主手",
    "Manage Waypoints": "管理航点",
    "MORNING": "早晨",
    "Most Fragments": "大多数片段",
    "Name:": "姓名：",
    "No Target Selected": "未选择目标",
    "No targets in sight": "看不到目标",
    "None": "没有任何",
    "NOTICE": "注意",
    "OBJECTIVES": "目标",
    "Objectives Completed": "目标完成",
    "objects you come across to learn new recipes. You can filter this list by including text after the": "你遇到的对象来学习新的配方。您可以通过在",
    "of 25 Slots Available": "25 个可用插槽",
    "OFFHAND": "副手",
    "or pressing": "或按",
    "or type": "或输入",
    "picks up a": "拿起一个",
    "Place Structure": "场所结构",
    "Plant Fiber": "植物纤维",
    "Plant Fibers": "植物纤维",
    "Preparing the grandest of adventures...": "准备最宏大的冒险...",
    "Press": "按",
    "QUESTS": "任务",
    "Quests & Reputation": "任务与声望",
    "QUICK ACTIONS": "快速行动",
    "random": "随机",
    "RECIPES": "配方",
    "Relica": "遗物",
    "Repair Kit": "修理包",
    "Resilience Rating": "弹性评级",
    "Rest Outdoors": "在户外休息",
    "Rest Outdoors?": "户外休息？",
    "Resting outdoors can be dangerous.": "在户外休息可能很危险。",
    "Resting restores health, increases mood, and eliminates fatigue. Being well-resting increases all stats by a small amount, while being sleepy lowers them.": "休息可以恢复生命值，增加情绪，消除疲劳。休息良好会少量增加所有统计数据，而困倦会降低它们。",
    "Right-Click to Approach": "右击接近",
    "Roll of Burlap": "粗麻布卷",
    "Rolls of Burlap": "粗麻布卷",
    "Room Size: 3": "房间大小：3",
    "Runefall334": "符文坠落334",
    "Runic Shards": "符文碎片",
    "Saving...": "保存...",
    "SE": "东南",
    "Search Area": "搜索",
    "server under the username": "用户名下的服务器",
    "Set waypoints by typing": "通过键入设置航点",
    "Settings & Options": "设置和选项",
    "Settlement": "沉降",
    "Shrouded Figure": "笼罩图",
    "Shrouded Figure": "笼罩图",
    "SHROUDED FIGURE": "笼罩图",
    "Soldier Ability:": "士兵能力：",
    "Soldiers gain increased damage resistance as their health decreases.": "随着生命值的降低，士兵的伤害抗性会增加。",
    "Soldiers have": "士兵有",
    "Speak with those you meet on your journey and learn how you might be able to help.": "与您在旅途中遇到的人交谈，了解您可以如何提供帮助。",
    "SPELLS": "法术",
    "Spells & Recipes": "咒语和配方",
    "STATUS": "状态",
    "Status:": "状态：",
    "Stealth": "隐身",
    "Stealthed": "隐身",
    "Sticks": "棍子",
    "Strength Rating": "力量等级",
    "Structure (Fixed)": "结构（固定）",
    "STRUCTURE SETTINGS": "结构设置",
    "tap": "轻敲",
    "TARGETING": "定位",
    "TARGETS": "目标",
    "Tattered Note": "破烂的纸条",
    "Tattered Note": "破烂的笔记",
    "THE BASICS": "基础知识",
    "The Jade Circle": "玉环",
    "The Jade Circle are known for their subtlety and influence. Their goal is to build alliances with powerful entities, forming a united front in the face of tyranny.": "玉界以其微妙和影响力而闻名。他们的目标是与强大的实体建立联盟，在暴政面前形成统一战线。",
    "The Radiant Hand": "光芒四射的手",
    "The Radiant Hand are known for their courage and strength. Their goal is to create a great machine of war capable of decimating any and all threats to the realm.": "光辉之手以其勇气和力量而闻名。他们的目标是创造一个伟大的战争机器，能够摧毁对这个领域的任何和所有威胁。",
    "The Will of the Wild": "野性的意志",
    "The Will of the Wild are known for their hard work and ingenuity. Their goal is to give true freedom to all, and empower every individual to choose their own destiny.": "野性意志以其辛勤工作和独创性而闻名。他们的目标是给予所有人真正的自由，并赋予每个人选择自己命运的权力。",
    "Tile x 10": "瓷砖 x 10",
    "Tin Shortsword": "锡短剑",
    "to attack, and": "攻击，和",
    "to change targets,": "改变目标，",
    "to close this message.": "关闭此消息。",
    "to get a random name. You can change your name at any time.": "得到一个随机的名字。您可以随时更改您的姓名。",
    "to interact,": "互动，",
    "to make a selection.": "进行选择。",
    "to move, press": "移动，按下",
    "to read the changelog.]": "阅读更新日志。]",
    "to see a full list of shortcuts and commands.": "查看快捷键和命令的完整列表。",
    "to skip character creation and start the game with a randomly generated character.": "跳过角色创建并使用随机生成的角色开始游戏。",
    "to take things. You can also": "拿东西。你也可以",
    "Traits": "性状",
    "TRAVELERS": "旅行者",
    "Type": "类型",
    "Type '": "类型 '",
    "Unknown to the Jade Circle": "玉界不为人知",
    "Unknown to the Radiant Hand": "光辉之手不知道",
    "Unknown to the Will of the Wild": "野性意志未知",
    "until Morning": "直到早上",
    "Use the": "使用",
    "vanishes!": "消失！",
    "View Area Map": "查看区域地图",
    "View Character": "查看角色",
    "View Inventory": "查看库存",
    "View Recipes": "查看配方",
    "View Spells & Abilities": "查看法术和能力",
    "View Waypoints": "查看航点",
    "Wait a Moment": "等一下",
    "Wall (Fixed)": "墙（固定）",
    "Water Attunement": "水调",
    "WAYPOINTS": "航点",
    "WEARING": "穿着",
    "What is your name?": "你叫什么名字？",
    "which": "哪个",
    "Winded": "缠绕",
    "Wooden Axe": "木斧",
    "Wooden Block": "木块",
    "Wooden Blocks": "木块",
    "Wooden Breastplate": "木制胸甲",
    "Wooden Breastplate": "木制胸甲",
    "Wooden Dagger": "木制匕首",
    "Wooden Fishing Rod": "木制钓鱼竿",
    "Wooden Log": "原木",
    "Wooden Pickaxe": "木镐",
    "Wooden Plank": "木板",
    "Wooden Planks": "木板",
    "Wooden Shovel": "木铲",
    "Wooden Torch": "木制手电筒",
    "WOODS": "树木",
    "Workbench": "工作台",
    "Wounded": "受伤",
    "You are": "你是",
    "You are concealed.": "你被隐藏了。",
    "You are no longer wounded.": "你不再受伤。",
    "You attempt to conceal yourself.": "你试图隐藏自己。",
    "You awaken refreshed!": "你醒来神清气爽！",
    "You can create local waypoints with": "您可以使用创建本地航点",
    "You can learn spells by reading tomes. Tomes can be found in the wild, or crafted by placing at least two runes on the ground and typing": "你可以通过阅读书籍来学习法术。 书籍可以在野外找到，或者通过在地面上放置至少两个符文并输入来制作",
    "You can track a specific waypoint on your compass by typing": "您可以通过键入来跟踪指南针上的特定航点",
    "You dash 5 steps to the south.": "你向南冲了 5 步。",
    "You do not have any items.": "您没有任何物品。",
    "You do not have any objectives.": "你没有任何目标。",
    "You find yourself in the wilderness. In the distance, you see a": "你发现自己身处荒野。 在远处，你看到一个",
    "You inspect a": "你检查一个",
    "You know 16 recipes.": "你知道16个配方。",
    "You lay down to rest.": "你躺下休息。",
    "You may also type": "您也可以输入",
    "You prepare to dash.": "你准备冲刺。",
    "You wait for a moment.": "你等一下。",
    "Your sleeping fades.": "你的睡眠消失了。",
    "[ number key ]": "[数字键]",
    "/(number)": "/（数字）",
    "2. Start New Adventure": "2.开始新的冒险",
    "3. Start New Adventure": "3.开始新的冒险",
    "Fragments:": "片段：",
    "Javan Softfist": "爪哇软拳",
    "Press the corresponding": "按相应的",
    "Score:": "分数：",
    "SELECT AN ADVENTURE": "选择冒险",
    "Soldier": "士兵",
    "Survived:": "幸存者：",
    "to select an adventure.": "选择一次冒险。",
    "-====}=+ WELCOME BACK TO FARA! +={====-": "-====}=+ 欢迎回到法拉！ +={====-",
    ",  and": "，  和",
    ". They are about your size. They bear markings associated with the": ".它们和你的大小差不多。它们带有与",
    "(Deletes Save Slot 1)": "（删除保存槽 1）",
    "<FIN": "<FIN",
    "1. Continue as Javan Softfist the Soldier": "1. 继续扮演 Javan Softfist the Soldier",
    "2. Back to Adventure Selection": "2. 回到冒险选择",
    "4 steps  to the south.": "向南走4步。",
    "5 steps  to the west.": "向西走5步。",
    "9. Start New Adventure": "9.开始新的冒险",
    "about five steps to the west.  It is  made of a very common material and is in perfect condition.": "向西大约五步。它由一种非常常见的材料制成，状况良好。",
    "about four steps to the south.  It is very small.": "向南大约四步。它非常小。",
    "Adventure!": "冒险！",
    "and hold it.": "并持有它。",
    "and wear it.": "并穿上它。",
    "Animal Bones": "动物骨头",
    "Approach Campfire": "接近篝火",
    "Approach Tin Shortsword": "接近锡短剑",
    "Banana Tree": "香蕉树",
    "Body": "身体",
    "Bone Breastplate": "骨胸甲",
    "Bone Shortsword": "骨短剑",
    "Bonus:": "奖金：",
    "Chunks of Ivory": "象牙块",
    "Clay Breastplate": "粘土胸甲",
    "Clay Shortsword": "粘土短剑",
    "Cook": "厨师",
    "Cook contents of Campfire": "营火的烹饪内容",
    "Copper Breastplate": "铜胸甲",
    "Copper Ingots": "铜锭",
    "Copper Shortsword": "铜短剑",
    "Dash to Campfire": "冲向营火",
    "Dash to Tin Shortsword": "Dash to Tin 短剑",
    "DEAD": "死的",
    "Deflects weapon projectiles": "偏转武器射弹",
    "enhances strength": "增强力量",
    "fortifies resilience": "增强弹性",
    "Glass Breastplate": "玻璃胸甲",
    "Glass Ingots": "玻璃锭",
    "Glass Shortsword": "玻璃短剑",
    "Heavy:": "重的：",
    "hinders finesse": "妨碍技巧",
    "Inspect Adventurer": "检查冒险家",
    "Inspect Campfire": "检查营火",
    "Inspect Tin Shortsword": "检查锡短剑",
    "Inventory": "存货",
    "INVENTORY/NEARBY": "库存/附近",
    "is engraved on it. This weapon requires strength to be effective, and its heavy attacks deflect weapon projectiles.  It is smaller than you. Equipping this": "刻在上面。这种武器需要力量才能发挥作用，它的重击会偏转武器射弹。它比你小。装备这个",
    "It is  made of a very common material and is in perfect condition. It is about your size. Wearing this on your body": "它由一种非常常见的材料制成，状况良好。它和你的大小差不多。把它戴在身上",
    "It is very small.": "它非常小。",
    "Ivory Breastplate": "象牙胸甲",
    "Ivory Shortsword": "象牙短剑",
    "Jade Circle faction.": "玉环派。",
    "Light": "光",
    "Light Campfire": "篝火晚会",
    "Material:": "材料：",
    "Mounds of Clay": "成堆的粘土",
    "Needs:": "需求：",
    "on a": "在一个",
    "Place Tin Shortsword in": "将锡短剑放入",
    "RES>": "资源>",
    "Salvage Campfire": "打捞营火",
    "Salvage Everything": "挽救一切",
    "Silver Breastplate": "银色胸甲",
    "Silver Ingots": "银锭",
    "Silver Shortsword": "银色短剑",
    "Size:": "尺寸：",
    "Slot:": "插槽：",
    "STR>": "力量>",
    "STR>>": "力量>>",
    "Strength": "力量",
    "Take  Adventurer": "冒险家",
    "The story of Javan Softfist the Soldier continues...": "士兵爪哇软拳的故事还在继续……",
    "They look strangely familiar. They appear to be a Soldier. They are": "他们看起来出奇的熟悉。他们似乎是一名士兵。他们是",
    "Tin Breastplate": "锡胸甲",
    "Tin Ingots": "锡锭",
    "Tin Shortsword": "锡短剑",
    "Tin, Very Common": "锡，非常常见",
    "View Inventory Details": "查看库存详情",
    "View Quests": "查看任务",
    "Wearing": "穿着",
    "Wood, Very Common": "木头，很常见",
    "Wooden Shortsword": "木制短剑",
    "You are  not holding anything.": "你什么都没有。",
    "You begin approaching a": "你开始接近一个",
    "You do not find anything.": "你什么也找不到。",
    "You learn how to make a Tin Shortsword and 7 similar recipes!": "您将学习如何制作锡制短剑和 7 个类似的食谱！",
    "You learn how to make a Wooden Breastplate and 7 similar recipes!": "您将学习如何制作木制胸甲和 7 个类似的食谱！",
    "You move  1 step  to the location of a": "你移动 1 步到一个位置",
    "You pick up a": "你拿起一个",
    "You pick up an": "你拿起一个",
    "You place your": "你把你的",
    "You search the area within 4 steps of you.": "您在 4 步内搜索该区域。",
    ". You need 3": ".你需要 3",
    "ACTIONS & GESTURES": "动作和手势",
    "ASTRAL BLESSING": "星光祝福",
    "ASTRAL CONVERSION": "星体转换",
    "Bone Breastplate": "骨胸甲",
    "Bone, Very Common": "骨头，很常见",
    "Burlap Satchel": "粗麻布挎包",
    "Burlap, Very Common": "粗麻布，很常见",
    "Capacity:": "容量：",
    "Causes the wielder to step backward": "使持用者后退",
    "CHA>>": "查>>",
    "Clay Breastplate": "粘土胸甲",
    "Clay, Very Common": "粘土，非常常见",
    "Clear Current Title": "清除当前标题",
    "Copper Breastplate": "铜胸甲",
    "Copper, Common": "铜，普通",
    "CURRENTLY EQUIPPED": "目前装备",
    "Dance": "舞蹈",
    "Day 2": "第 2 天",
    "Deals increased damage": "造成更多伤害",
    "End Stealth": "结束隐身",
    "Glass Breastplate": "玻璃胸甲",
    "Glass, Common": "玻璃，普通",
    "INS>>": "插件>>",
    "Inventory Details": "库存详情",
    "is 5 kilometers to the south": "向南 5 公里",
    "ITEMS & EQUIPMENT": "物品和设备",
    "Ivory Breastplate": "象牙胸甲",
    "Ivory, Common": "象牙色，普通",
    "Jump/Dodge": "跳跃/闪避",
    "Mark Area": "标记区域",
    "Read": "读",
    "Read Tattered Note": "阅读破烂的纸条",
    "RELICA": "雷利卡",
    "Repair Kit": "修理包",
    "RES>>": "资源>>",
    "Roald Whisperblade the Soldier": "Roald Whisperblade the Soldier",
    "Roll of Burlap": "粗麻布卷",
    "Rosestrike720": "玫瑰罢工720",
    "Salvage Wooden Breastpl...": "打捞木制胸罩",
    "Set Title to Unknown to the Jade Circle": "将标题设置为翡翠圈未知",
    "Set Title to Unknown to the Radiant Hand": "将标题设置为辐射之手未知",
    "Set Title to Unknown to the Will of the Wild": "将标题设置为野蛮意志未知",
    "SHRUBLAND": "灌木丛",
    "Silver Breastplate": "银色胸甲",
    "Silver, Common": "银，普通",
    "Strength or Finesse": "力量或技巧",
    "Structure": "结构",
    "Take": "拿",
    "Take  Tattered Note": "记破烂笔记",
    "Take  Wooden Breastpl...": "以木制胸针...",
    "Take Everything": "拿走一切",
    "They are often used to craft or repair items high quality items.": "它们通常用于制作或修理高品质物品。",
    "They are typically used to repair damaged items.": "它们通常用于修复损坏的物品。",
    "Tile": "瓦",
    "Tin Breastplate": "锡胸甲",
    "Track 'Relica'' on Compass": "在指南针上追踪“遗物”",
    "Travel to 'Relica'": "前往“遗迹”",
    "UNKNOWN TO THE JADE CIRCLE": "玉界不为人知",
    "UNKNOWN TO THE RADIANT HAND": "未知的光芒四射的手",
    "UNKNOWN TO THE WILL OF THE WILD": "未知的野性意志",
    "Use Astral Blessing": "使用星界祝福",
    "Use Astral Conversion": "使用星界转换",
    "View Factions & Titles": "查看派系和头衔",
    "View Jade Circle Traits": "查看玉环特征",
    "View Radiant Hand Traits": "查看光芒四射的手部特征",
    "View Will of the Wild Traits": "查看狂野意志特质",
    "Wall": "墙",
    "Will of the Wild faction.": "野性意志派系。",
    "Wooden Axe": "木斧",
    "Wooden Block": "木块",
    "Wooden Dagger": "木匕首",
    "Wooden Fishing Rod": "木制钓鱼竿",
    "Wooden Pickaxe": "木镐",
    "Wooden Plank": "木板",
    "Wooden Shovel": "木铲",
    "Wooden Torch": "木制火炬",
    "You arise with new purpose!": "你带着新的目的出现！",
    "You do not have the right materials in range to make a": "您没有合适的材料来制作",
    "Roald Whisperblade": "罗尔德·耳语之刃",
    "1. Continue as Roald Whisperblade the Soldier": "1. 继续扮演士兵罗尔德·耳语之刃",
    "The story of Roald Whisperblade the Soldier continues...": "士兵 罗尔德·耳语之刃 的故事还在继续……",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "You have very short, kinky, red hair and big pale eyes. You are rather short.  You came from squalid conditions in a tiny hamlet far to the east and were raised by a wise couple. In your earlier years, you spent most your time begging on the street. One of your most notable memories was the time you tried to join the military, but were rejected for being too idealistic. Recently, you have been hesitant to trust others, and are not very loud. When faced with opposition, you often over-complicate things.": "你有一头非常短的、卷曲的、红色的头发和苍白的大眼睛。 你比较矮。 你来自东方遥远的一个小村庄的肮脏条件，由一对聪明的夫妇抚养长大。 在你早年，你大部分时间都在街头乞讨。 你最显着的记忆之一是你试图参军，但因为过于理想主义而被拒绝。 最近，你一直在犹豫是否相信别人，声音也不大。 当面对反对时，你常常把事情复杂化。",
    "You have long, curly, blonde hair and cloudy hazel eyes. You are rather short and lean.  You came from modest conditions in a tiny uncharted territory far to the south and were raised by a very practical community. When you were younger, most of your time was spent learning from thieves. One of your most notable memories was the time you won a poetry contest. Recently, you have been eager to trust others, and are not very timid. When faced with opposition, you often act without hesitation.": "你有一头卷曲的金色长发和朦胧的淡褐色眼睛。 你很矮很瘦。 你来自遥远的南方一个未知的小领土，条件适中，并由一个非常实际的社区抚养长大。 当你年轻的时候，你大部分时间都花在向小偷学习上。 你最显着的记忆之一是你赢得诗歌比赛的那次。 最近，你渴望信任别人，也不是很胆小。 面对反对时，你往往会毫不犹豫地采取行动。",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "W": "W",
    "U": "U",
    "O": "O",
    "S": "S",
    "SE": "SE",
    "E": "E",
    "D": "D",
    "H": "H",
    "A": "A",
    "[Discord]": "[Discord]",
    "SW": "SW",
    "© 2016-2021 @BrianIsCreative": "© 2016-2021 @BrianIsCreative",
    "<": "<",
    ">": ">",
    "the": "",
    "NW": "NW",
    "[@BrianIsCreative]": "[@BrianIsCreative]",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Wooden Plank x ": "木板 x ",
    "Wooden Block x ": "木块 x ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+). $/,
    /^([\d\.]+)km$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\[([\d\.,]+)\]$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You know (.+) recipes.$/, '你知道16个配方。'],
    [/^You dash (.+) steps to the west.$/, '你向西冲了 $1 步。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) day, ([\d\.,]+) hours$/, '$1 天，$2 小时'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);