/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Version": "版本",
    "-====}=+ WELCOME TO FARA! +={====-": "-====}=+ 欢迎来到 FARA! +={====-",
    "Preparing the grandest of adventures...": "",
    "MAP": "地图",
    ",  and a": ", 和一个",
    ", a": "， 一个",
    ", and": "， 和",
    ", and go to them with": "，然后去他们那里",
    ", or": "， 或者",
    ", press": "， 按",
    ", remove them with": ", 删除它们",
    ", type": "， 类型",
    "! CAPSLOCK ON !": "！大写锁定！",
    ". FARA also submits error reports": ". FARA 还提交错误报告",
    ". It is": ".这是",
    ". It is imbued with arcane energy.  It is about your size.": ".它充满了奥术能量。它和你的大小差不多。",
    ". They start their journey with": ".他们开始他们的旅程",
    ". To disable sharing your adventures with our highly supportive community, type": ".要禁用与我们高度支持的社区分享您的冒险经历，请输入",
    "...A": "...一个",
    "' or": "' 或者",
    "' to create the listed item.": "' 以创建列出的物品。",
    "'. Type '": "'。类型 '",
    "'Name'": "'名称'",
    "'Number'": "'数字'",
    "(gray)": "（灰色）",
    "(Soldier)": "（士兵）",
    ")": ")",
    "[ 1 ]": "[ 1 ]",
    "[ a ]": "[ a ]",
    "[ Arrow Keys ]": "[ 方向键 ]",
    "[ e ]": "[e]",
    "[ Esc ]": "[ Esc键 ]",
    "[ r ]": "[r]",
    "[ shift + p ]": "[ shift + p ]",
    "[ t ]": "[t]",
    "[ Tab ]": "[ Tab ]",
    "[Click here or type": "[点击这里或输入",
    "0 days, 0 hours": "0天0小时",
    "0 days, 1 hour": "0天1小时",
    "0.0.16.5d": "0.0.16.5d",
    "0.0.16.5d Browser": "0.0.16.5d 浏览器",
    "1 Spell Slot": "1 个法术位",
    "3. Cancel": "3. 取消",
    "A glowing, viscous liquid oozes from this ghostly apparition's eyes and mouth.": "一种发光的粘稠液体从这个幽灵的眼睛和嘴里渗出。",
    "about nine steps to the south. A glowing, viscous liquid oozes from this ghostly apparition's eyes and mouth.  It is  holding an": "向南大约九步。一种发光的粘稠液体从这个幽灵的眼睛和嘴里渗出。它拿着一个",
    "Above Average": "高于平均水平",
    "Above Average Health": "高于平均水平",
    "Above Average Resilience": "高于平均弹性",
    "ACCESSORY": "配饰",
    "Actions & Gestures": "动作和手势",
    "Adamantine Scythe": "金刚镰刀",
    "Adventurer": "冒险家",
    "Air Attunement": "空气调谐",
    "All Rights Reserved": "版权所有",
    "An": "一个",
    "AN ENCOUNTER!": "一次邂逅！",
    "and": "和",
    "Approach Shrouded Figure": "接近笼罩图",
    "Approach Tattered Note": "接近破烂的笔记",
    "Approach Wooden Breastpl...": "接近木制胸罩",
    "Arcane": "奥术",
    "Artifacts Recovered": "恢复的文物",
    "Ash Tree": "白蜡树",
    "Astral Blessing": "星体祝福",
    "Astral Conversion": "星体转换",
    "Average": "平均",
    "B!": "乙！",
    "Below Average": "低于平均水平",
    "Below Average Insight": "低于平均水平的洞察力",
    "BODY": "身体",
    "Burlap Satchel": "粗麻布挎包",
    "Campfire": "营火",
    "Campfire (Fixed)": "营火（固定）",
    "Cancel": "取消",
    "Charm Rating": "魅力评级",
    "Clear waypoints you no longer need by typing": "通过键入清除不再需要的航点",
    "click": "点击",
    "click anywhere in the middle of the screen": "单击屏幕中间的任意位置",
    "click anywhere in the middle of the screen and select 'Get Random Adventurer'": "单击屏幕中间的任意位置并选择“获取随机冒险者”",
    "click outside of this window": "在此窗口外点击",
    "command. The number in": "命令。数字在",
    "Compare Items": "比较物品",
    "Condition:": "状况：",
    "Conditions:": "状况：",
    "Consumes a single Key Fragment to permanently increase an ability score of your choosing": "消耗一个关键碎片来永久增加你选择的能力值",
    "Consumes ALL collected Key Fragments to completely restore the caster and damage nearby enemies": "消耗所有收集的钥匙碎片以完全恢复施法者并伤害附近的敌人",
    "Current Score": "当前分数",
    "Damage Reduction": "减少伤害",
    "Darkness Attunement": "黑暗调和",
    "Dash": "短跑",
    "Dash to Shrouded Figure": "破折号到笼罩图",
    "Dash to Tattered Note": "破破烂烂的纸条",
    "Dash to Wooden Breastpl...": "Dash to 木制胸罩",
    "Days Survived": "生存天数",
    "Desired Name": "所需名称",
    "Destealth": "解除隐身",
    "Details:": "详情：",
    "dies by bleeding.": "死于流血。",
    "Distance Traveled": "旅行距离",
    "DM2": "DM2",
    "Dodge": "躲闪",
    "Dogged March": "顽强的三月",
    "DOGGED MARCH": "顽强的三月",
    "drag": "拖",
    "drops a": "滴一个",
    "Dungeons Cleared": "地下城通关",
    "Earth Attunement": "地球调谐",
    "Element:": "元素：",
    "elements around the interface to perform most actions. Type": "界面周围的元素以执行大多数操作。类型",
    "Engaging it in combat would surely be your undoing.": "将它投入战斗肯定会是你的毁灭。",
    "Entrance: N": "入口：N",
    "Exit Area": "出口区",
    "FACTIONS": "派系",
    "FARA is a game about exploration and discovery. It's light on visuals, so you are encouraged to imagine what's described in the coolest way possible.": "FARA 是一款关于探索和发现的游戏。它在视觉上很轻松，因此鼓励您以最酷的方式想象所描述的内容。",
    "FARA shares your accomplishments to a": "FARA 将您的成就分享给",
    "FEET": "脚",
    "Finesse Rating": "技巧等级",
    "Fire Attunement": "火调",
    "Friends Made": "结交朋友",
    "Gain increased damage resistance as health decreases": "随着生命值的降低，获得更高的伤害抗性",
    "GAME LOCKED - New Instance Detected": "游戏锁定 - 检测到新实例",
    "Get Random Adventurer": "获得随机冒险者",
    "Get Random Name": "获取随机名称",
    "ghostly figure": "鬼影",
    "Good": "好的",
    "Good luck out there. -": "祝你好运。 -",
    "Good Strength": "强度好",
    "HANDS": "手",
    "HEAD": "头",
    "Health": "生命值",
    "Healthy": "生命值",
    "help me fix bugs. To disable this, type": "帮我修复错误。要禁用此功能，请键入",
    "High Score": "高分",
    "HOLDING": "当前",
    "Hostile": "敌对的",
    "indicates how many of a given material you have on you or within reach.": "表示您拥有或触手可及的给定材料的数量。",
    "Insight Rating": "洞察力评级",
    "Inspect": "检查",
    "Inspect Shrouded Figure": "检查遮蔽图",
    "Inspect Tattered Note": "检查破烂的纸条",
    "Inspect Wooden Breastpl...": "检查木制胸甲...",
    "INVENTORY": "库存",
    "is 14 kilometers to the north": "向北 14 公里",
    "is bleeding heavily!": "正在大量流血！",
    "It is  8 steps out of your attack range.": "它在你的攻击范围之外 8 步。",
    "item name": "物品名",
    "ITEMS": "物品",
    "Items & Equipment": "物品和装备",
    "Items Discovered": "发现的物品",
    "Javan Softfist the Soldier": "士兵爪哇软拳",
    "Key Fragment": "关键片段",
    "Key Fragment": "关键片段",
    "Key Fragments": "关键片段",
    "Known Spells": "已知法术",
    "Learned Spells (0/1)": "学习法术 (0/1)",
    "Light Attunement": "光调",
    "Lives Taken": "夺走生命",
    "Look Around": "环视四周",
    "looming over an injured adventurer.": "逼近受伤的冒险者。",
    "MAIN MENU": "主菜单",
    "MAINHAND": "主手",
    "Manage Waypoints": "管理航点",
    "MORNING": "早晨",
    "Most Fragments": "大多数片段",
    "Name:": "名称：",
    "No Target Selected": "未选择目标",
    "No targets in sight": "看不到目标",
    "None": "没有任何",
    "NOTICE": "注意",
    "OBJECTIVES": "目标",
    "Objectives Completed": "目标完成",
    "objects you come across to learn new recipes. You can filter this list by including text after the": "你遇到的对象来学习新的配方。您可以通过在",
    "of 25 Slots Available": "25 个可用插槽",
    "OFFHAND": "副手",
    "or pressing": "或按",
    "or type": "或输入",
    "picks up a": "拿起一个",
    "Place Structure": "场所结构",
    "Plant Fiber": "植物纤维",
    "Plant Fibers": "植物纤维",
    "Preparing the grandest of adventures...": "准备最宏大的冒险...",
    "Press": "按",
    "QUESTS": "任务",
    "Quests & Reputation": "任务与声望",
    "QUICK ACTIONS": "快速行动",
    "random": "随机",
    "RECIPES": "配方",
    "Relica": "遗物",
    "Repair Kit": "修理包",
    "Resilience Rating": "弹性评级",
    "Rest Outdoors": "在户外休息",
    "Rest Outdoors?": "户外休息？",
    "Resting outdoors can be dangerous.": "在户外休息可能很危险。",
    "Resting restores health, increases mood, and eliminates fatigue. Being well-resting increases all stats by a small amount, while being sleepy lowers them.": "休息可以恢复生命值，增加情绪，消除疲劳。休息良好会少量增加所有统计数据，而困倦会降低它们。",
    "Right-Click to Approach": "右击接近",
    "Roll of Burlap": "粗麻布卷",
    "Rolls of Burlap": "粗麻布卷",
    "Room Size: 3": "房间大小：3",
    "Runefall334": "符文坠落334",
    "Runic Shards": "符文碎片",
    "Saving...": "保存...",
    "SE": "东南",
    "Search Area": "搜索",
    "server under the username": "用户名下的服务器",
    "Set waypoints by typing": "通过键入设置航点",
    "Settings & Options": "设置和选项",
    "Settlement": "沉降",
    "Shrouded Figure": "笼罩图",
    "Shrouded Figure": "笼罩图",
    "SHROUDED FIGURE": "笼罩图",
    "Soldier Ability:": "士兵能力：",
    "Soldiers gain increased damage resistance as their health decreases.": "随着生命值的降低，士兵的伤害抗性会增加。",
    "Soldiers have": "士兵有",
    "Speak with those you meet on your journey and learn how you might be able to help.": "与您在旅途中遇到的人交谈，了解您可以如何提供帮助。",
    "SPELLS": "法术",
    "Spells & Recipes": "咒语和配方",
    "STATUS": "状态",
    "Status:": "状态：",
    "Stealth": "隐身",
    "Stealthed": "隐身",
    "Sticks": "棍子",
    "Strength Rating": "力量等级",
    "Structure (Fixed)": "结构（固定）",
    "STRUCTURE SETTINGS": "结构设置",
    "tap": "轻敲",
    "TARGETING": "目标",
    "TARGETS": "目标",
    "Tattered Note": "破烂的纸条",
    "Tattered Note": "破烂的笔记",
    "THE BASICS": "基础知识",
    "The Jade Circle": "玉环",
    "The Jade Circle are known for their subtlety and influence. Their goal is to build alliances with powerful entities, forming a united front in the face of tyranny.": "玉界以其微妙和影响力而闻名。他们的目标是与强大的实体建立联盟，在暴政面前形成统一战线。",
    "The Radiant Hand": "光芒四射的手",
    "The Radiant Hand are known for their courage and strength. Their goal is to create a great machine of war capable of decimating any and all threats to the realm.": "光辉之手以其勇气和力量而闻名。他们的目标是创造一个伟大的战争机器，能够摧毁对这个领域的任何和所有威胁。",
    "The Will of the Wild": "野性的意志",
    "The Will of the Wild are known for their hard work and ingenuity. Their goal is to give true freedom to all, and empower every individual to choose their own destiny.": "野性意志以其辛勤工作和独创性而闻名。他们的目标是给予所有人真正的自由，并赋予每个人选择自己命运的权力。",
    "Tile x 10": "瓷砖 x 10",
    "Tin Shortsword": "锡制短剑",
    "to attack, and": "攻击，和",
    "to change targets,": "改变目标，",
    "to close this message.": "关闭此消息。",
    "to get a random name. You can change your name at any time.": "得到一个随机的名字。您可以随时更改您的名称。",
    "to interact,": "互动，",
    "to make a selection.": "进行选择。",
    "to move, press": "移动，按下",
    "to read the changelog.]": "阅读更新日志。]",
    "to see a full list of shortcuts and commands.": "查看快捷键和命令的完整列表。",
    "to skip character creation and start the game with a randomly generated character.": "跳过角色创建并使用随机生成的角色开始游戏。",
    "to take things. You can also": "拿东西。你也可以",
    "Traits": "性状",
    "TRAVELERS": "旅行者",
    "Type": "类型",
    "Type '": "类型 '",
    "Unknown to the Jade Circle": "玉界不为人知",
    "Unknown to the Radiant Hand": "光辉之手不知道",
    "Unknown to the Will of the Wild": "野性意志未知",
    "until Morning": "直到早上",
    "Use the": "使用",
    "vanishes!": "消失！",
    "View Area Map": "查看区域地图",
    "View Character": "查看角色",
    "View Inventory": "查看库存",
    "View Recipes": "查看配方",
    "View Spells & Abilities": "查看法术和能力",
    "View Waypoints": "查看航点",
    "Wait a Moment": "等一下",
    "Wall (Fixed)": "墙（固定）",
    "Water Attunement": "水调",
    "WAYPOINTS": "航点",
    "WEARING": "穿着",
    "What is your name?": "你叫什么名字？",
    "which": "哪个",
    "Winded": "缠绕",
    "Wooden Axe": "木斧",
    "Wooden Block": "木块",
    "Wooden Blocks": "木块",
    "Wooden Breastplate": "木制胸甲",
    "Wooden Breastplate": "木制胸甲",
    "Wooden Dagger": "木制匕首",
    "Wooden Fishing Rod": "木制钓鱼竿",
    "Wooden Log": "原木",
    "Wooden Pickaxe": "木镐",
    "Wooden Plank": "木板",
    "Wooden Planks": "木板",
    "Wooden Shovel": "木铲",
    "Wooden Torch": "木制手电筒",
    "WOODS": "树木",
    "Workbench": "工作台",
    "Wounded": "受伤",
    "You are": "你是",
    "You are concealed.": "你被隐藏了。",
    "You are no longer wounded.": "你不再受伤。",
    "You attempt to conceal yourself.": "你试图隐藏自己。",
    "You awaken refreshed!": "你醒来神清气爽！",
    "You can create local waypoints with": "您可以使用创建本地航点",
    "You can learn spells by reading tomes. Tomes can be found in the wild, or crafted by placing at least two runes on the ground and typing": "你可以通过阅读书籍来学习法术。 书籍可以在野外找到，或者通过在地面上放置至少两个符文并输入来制作",
    "You can track a specific waypoint on your compass by typing": "您可以通过键入来跟踪指南针上的特定航点",
    "You dash 5 steps to the south.": "你向南冲了 5 步。",
    "You do not have any items.": "您没有任何物品。",
    "You do not have any objectives.": "你没有任何目标。",
    "You find yourself in the wilderness. In the distance, you see a": "你发现自己身处荒野。 在远处，你看到一个",
    "You inspect a": "你检查一个",
    "You know 16 recipes.": "你知道16个配方。",
    "You lay down to rest.": "你躺下休息。",
    "You may also type": "您也可以输入",
    "You prepare to dash.": "你准备冲刺。",
    "You wait for a moment.": "你等一下。",
    "Your sleeping fades.": "你的睡眠消失了。",
    "[ number key ]": "[数字键]",
    "2. Start New Adventure": "2.开始新的冒险",
    "3. Start New Adventure": "3.开始新的冒险",
    "Fragments:": "片段：",
    "Javan Softfist": "爪哇软拳",
    "Press the corresponding": "按相应的",
    "Score:": "分数：",
    "SELECT AN ADVENTURE": "选择冒险",
    "Soldier": "士兵",
    "Survived:": "幸存者：",
    "to select an adventure.": "选择一次冒险。",
    "-====}=+ WELCOME BACK TO FARA! +={====-": "-====}=+ 欢迎回到法拉！ +={====-",
    ",  and": "，  和",
    ". They are about your size. They bear markings associated with the": ".它们和你的大小差不多。它们带有与",
    "(Deletes Save Slot 1)": "（删除保存槽 1）",
    "<FIN": "<FIN",
    "1. Continue as Javan Softfist the Soldier": "1. 继续扮演 Javan Softfist the Soldier",
    "2. Back to Adventure Selection": "2. 回到冒险选择",
    "4 steps  to the south.": "向南走4步。",
    "5 steps  to the west.": "向西走5步。",
    "9. Start New Adventure": "9.开始新的冒险",
    "about five steps to the west.  It is  made of a very common material and is in perfect condition.": "向西大约五步。它由一种非常常见的材料制成，状况良好。",
    "about four steps to the south.  It is very small.": "向南大约四步。它非常小。",
    "Adventure!": "冒险！",
    "and hold it.": "并持有它。",
    "and wear it.": "并穿上它。",
    "Animal Bones": "动物骨头",
    "Approach Campfire": "接近营火",
    "Approach Tin Shortsword": "接近锡制短剑",
    "Banana Tree": "香蕉树",
    "Body": "身体",
    "Bone Breastplate": "骨胸甲",
    "Bone Shortsword": "骨短剑",
    "Bonus:": "奖励：",
    "Chunks of Ivory": "象牙块",
    "Clay Breastplate": "粘土胸甲",
    "Clay Shortsword": "粘土短剑",
    "Cook": "厨师",
    "Cook contents of Campfire": "营火的烹饪内容",
    "Copper Breastplate": "铜胸甲",
    "Copper Ingots": "铜锭",
    "Copper Shortsword": "铜短剑",
    "Dash to Campfire": "冲向营火",
    "Dash to Tin Shortsword": "Dash to Tin 短剑",
    "DEAD": "死亡",
    "Deflects weapon projectiles": "偏转武器射弹",
    "enhances strength": "增强力量",
    "fortifies resilience": "增强弹性",
    "Glass Breastplate": "玻璃胸甲",
    "Glass Ingots": "玻璃锭",
    "Glass Shortsword": "玻璃短剑",
    "Heavy:": "重的：",
    "hinders finesse": "妨碍技巧",
    "Inspect Adventurer": "检查冒险家",
    "Inspect Campfire": "检查营火",
    "Inspect Tin Shortsword": "检查锡制短剑",
    "Inventory": "存货",
    "INVENTORY/NEARBY": "库存/附近",
    "is engraved on it. This weapon requires strength to be effective, and its heavy attacks deflect weapon projectiles.  It is smaller than you. Equipping this": "刻在上面。这种武器需要力量才能发挥作用，它的重击会偏转武器射弹。它比你小。装备这个",
    "It is  made of a very common material and is in perfect condition. It is about your size. Wearing this on your body": "它由一种非常常见的材料制成，状况良好。它和你的大小差不多。把它戴在身上",
    "It is very small.": "它非常小。",
    "Ivory Breastplate": "象牙胸甲",
    "Ivory Shortsword": "象牙短剑",
    "Jade Circle faction.": "玉环派。",
    "Light": "光明",
    "Light Campfire": "营火晚会",
    "Material:": "材料：",
    "Mounds of Clay": "成堆的粘土",
    "Needs:": "需求：",
    "on a": "在一个",
    "Place Tin Shortsword in": "将锡制短剑放入",
    "RES>": "资源>",
    "Salvage Campfire": "搜索营火",
    "Salvage Everything": "挽救一切",
    "Silver Breastplate": "银色胸甲",
    "Silver Ingots": "银锭",
    "Silver Shortsword": "银色短剑",
    "Size:": "尺寸：",
    "Slot:": "插槽：",
    "STR>": "力量>",
    "STR>>": "力量>>",
    "Strength": "力量",
    "Take  Adventurer": "成为冒险家",
    "The story of Javan Softfist the Soldier continues...": "士兵爪哇软拳的故事还在继续……",
    "They look strangely familiar. They appear to be a Soldier. They are": "他们看起来出奇的熟悉。他们似乎是一名士兵。他们是",
    "Tin Breastplate": "锡胸甲",
    "Tin Ingots": "锡锭",
    "Tin Shortsword": "锡制短剑",
    "Tin, Very Common": "锡，非常常见",
    "View Inventory Details": "查看库存详情",
    "View Quests": "查看任务",
    "Wearing": "穿着",
    "Wood, Very Common": "木头，很常见",
    "Wooden Shortsword": "木制短剑",
    "You are  not holding anything.": "你什么都没有。",
    "You begin approaching a": "你开始接近一个",
    "You do not find anything.": "你什么也找不到。",
    "You learn how to make a Tin Shortsword and 7 similar recipes!": "您将学习如何制作锡制短剑和 7 个类似的食谱！",
    "You learn how to make a Wooden Breastplate and 7 similar recipes!": "您将学习如何制作木制胸甲和 7 个类似的食谱！",
    "You move  1 step  to the location of a": "你移动 1 步到一个位置",
    "You pick up a": "你拿起一个",
    "You pick up an": "你拿起一个",
    "You place your": "你把你的",
    "You search the area within 4 steps of you.": "您在 4 步内搜索该区域。",
    ". You need 3": ".你需要 3",
    "ACTIONS & GESTURES": "动作和手势",
    "ASTRAL BLESSING": "星光祝福",
    "ASTRAL CONVERSION": "星体转换",
    "Bone Breastplate": "骨胸甲",
    "Bone, Very Common": "骨头，很常见",
    "Burlap Satchel": "粗麻布挎包",
    "Burlap, Very Common": "粗麻布，很常见",
    "Capacity:": "容量：",
    "Causes the wielder to step backward": "使持用者后退",
    "CHA>>": "查>>",
    "Clay Breastplate": "粘土胸甲",
    "Clay, Very Common": "粘土，非常常见",
    "Clear Current Title": "清除当前标题",
    "Copper Breastplate": "铜胸甲",
    "Copper, Common": "铜，普通",
    "CURRENTLY EQUIPPED": "目前装备",
    "Dance": "舞蹈",
    "Day 2": "第 2 天",
    "Deals increased damage": "造成更多伤害",
    "End Stealth": "结束隐身",
    "Glass Breastplate": "玻璃胸甲",
    "Glass, Common": "玻璃，普通",
    "INS>>": "插件>>",
    "Inventory Details": "库存详情",
    "is 5 kilometers to the south": "向南 5 公里",
    "ITEMS & EQUIPMENT": "物品和装备",
    "Ivory Breastplate": "象牙胸甲",
    "Ivory, Common": "象牙色，普通",
    "Jump/Dodge": "跳跃/闪避",
    "Mark Area": "标记区域",
    "Read": "读",
    "Read Tattered Note": "阅读破烂的纸条",
    "RELICA": "雷利卡",
    "Repair Kit": "修理包",
    "RES>>": "资源>>",
    "Roald Whisperblade the Soldier": "Roald Whisperblade the Soldier",
    "Roll of Burlap": "粗麻布卷",
    "Rosestrike720": "玫瑰罢工720",
    "Salvage Wooden Breastpl...": "分解木制胸甲",
    "Set Title to Unknown to the Jade Circle": "将标题设置为翡翠圈未知",
    "Set Title to Unknown to the Radiant Hand": "将标题设置为辐射之手未知",
    "Set Title to Unknown to the Will of the Wild": "将标题设置为野蛮意志未知",
    "SHRUBLAND": "灌木丛",
    "Silver Breastplate": "银色胸甲",
    "Silver, Common": "银，普通",
    "Strength or Finesse": "力量或技巧",
    "Structure": "结构",
    "Take": "拿走",
    "Take  Tattered Note": "记破烂笔记",
    "Take  Wooden Breastpl...": "以木制胸针...",
    "Take Everything": "拿走一切",
    "They are often used to craft or repair items high quality items.": "它们通常用于制作或修理高品质物品。",
    "They are typically used to repair damaged items.": "它们通常用于修复损坏的物品。",
    "Tile": "瓦",
    "Tin Breastplate": "锡胸甲",
    "Track 'Relica'' on Compass": "在指南针上追踪“遗物”",
    "Travel to 'Relica'": "前往“遗迹”",
    "UNKNOWN TO THE JADE CIRCLE": "玉界不为人知",
    "UNKNOWN TO THE RADIANT HAND": "未知的光芒四射的手",
    "UNKNOWN TO THE WILL OF THE WILD": "未知的野性意志",
    "Use Astral Blessing": "使用星界祝福",
    "Use Astral Conversion": "使用星界转换",
    "View Factions & Titles": "查看派系和头衔",
    "View Jade Circle Traits": "查看玉环特征",
    "View Radiant Hand Traits": "查看光芒四射的手部特征",
    "View Will of the Wild Traits": "查看狂野意志特质",
    "Wall": "墙",
    "Will of the Wild faction.": "野性意志派系。",
    "Wooden Axe": "木斧",
    "Wooden Block": "木块",
    "Wooden Dagger": "木匕首",
    "Wooden Fishing Rod": "木制钓鱼竿",
    "Wooden Pickaxe": "木镐",
    "Wooden Plank": "木板",
    "Wooden Shovel": "木铲",
    "Wooden Torch": "木制火炬",
    "You arise with new purpose!": "你带着新的目的出现！",
    "You do not have the right materials in range to make a": "您没有合适的材料来制作",
    "Roald Whisperblade": "罗尔德·耳语之刃",
    "1. Continue as Roald Whisperblade the Soldier": "1. 继续扮演士兵罗尔德·耳语之刃",
    "The story of Roald Whisperblade the Soldier continues...": "士兵 罗尔德·耳语之刃 的故事还在继续……",
    "- Adventurers have an increased chance to find rare items. They also have the Heroic Feat ability which provides a temporary boost to all stats once per rest.": "- 冒险家找到稀有物品的机会增加。他们还具有英雄壮举能力，每次休息一次可以暂时提升所有统计数据。",
    "- Fishmongers cannot drown, take greatly reduced damage while Intoxicated and are immune to the negative effects, and have a higher chance to catch rare items while fishing.": "- 鱼贩不会溺水，在陶醉时受到的伤害大大降低，并且不受负面影响，并且在钓鱼时有更高的几率捕获稀有物品。",
    "- Gatekeepers will deflect long-range projectiles, and their shields and armor take less damage in combat. They also have the Protect ability which temporarily reduces the amount of damage a target takes by half.": "- 守门人会偏转远程射弹，他们的盾牌和盔甲在战斗中受到的伤害更少。它们还具有保护能力，可以暂时将目标受到的伤害减半。",
    "- Ragamuffins have an increased chance to steal successfully, and can find a wider variety of items. In combat, Ragamuffins can attempt to /steal weapons used to attack them.": "- 拉格玛芬 成功偷窃的机会增加，并且可以找到更多种类的物品。在战斗中，拉格玛芬 可以尝试/窃取用来攻击它们的武器。",
    "- Soldiers gain increased damage resistance as their health decreases.": "- 随着生命值的降低，士兵的伤害抗性会增加。",
    "- The unemployed can type": "- 失业者可以打字",
    "- Tourists gain a small amount of health and mood when moving to a new area, can remember five times the normal number of waypoints.": "- 游客在移动到一个新的区域时会获得少量的健康和情绪，可以记住五倍于正常数量的航点。",
    "- While under attack, stray cats will occasionally come to the aid of Cat Whisperers. They can also talk to cats.": "- 在受到攻击时，流浪猫偶尔会来帮助猫语者。他们也可以和猫说话。",
    ". Type": ".类型",
    "' is not a valid command.": "' 不是有效的命令。",
    "(Adventurer)": "（冒险家）",
    "(Filtering 1 Targets)": "（过滤 1 个目标）",
    "(Filtering 2 Targets)": "（过滤 2 个目标）",
    "(Filtering 3 Targets)": "（过滤 3 个目标）",
    "(Major)": "（主要的）",
    "(Minor)": "（次要的）",
    "1. I am an Adventurer.": "1. 我是冒险者。",
    "2 Spell Slots": "2 个法术位",
    "2. I am something else.": "2. 我是别的东西。",
    "3 Spell Slots": "3 个法术位",
    "about nine steps to the southeast. A glowing, viscous liquid oozes from this ghostly apparition's eyes and mouth.  It is  holding an": "向东南约九步。一种发光的粘稠液体从这个幽灵的眼睛和嘴里渗出。它拿着一个",
    "Above Average Charm": "高于平均水平的魅力",
    "Above Average Finesse": "高于平均水平",
    "Above Average Insight": "高于平均水平的洞察力",
    "ADVENTURER": "冒险家",
    "Adventurer Ability:": "冒险者能力：",
    "Adventurers have an increased chance to find rare items. They also have the Heroic Feat ability which provides a temporary boost to all stats once per rest.": "冒险者找到稀有物品的机会增加。他们还具有英雄壮举能力，每次休息一次可以暂时提升所有统计数据。",
    "Adventurers have Average Health and": "冒险者的健康和",
    "Agronomist": "农学家",
    "Allows crafted spells to start two tiers higher than normal": "允许精心制作的法术开始比正常高两层",
    "Allows entities with at least half of their stamina to stealth while in combat": "允许拥有至少一半耐力的实体在战斗中隐身",
    "Allows higher quality recipes to be learned from object inspection or acquisition": "允许从对象检查或获取中学习更高质量的配方",
    "Allows the inspection of target inventories": "允许检查目标库存",
    "Analyzer": "分析仪",
    "Angler": "垂钓者",
    "Appraiser": "估价师",
    "Approach Adventurer": "接近冒险家",
    "ARE YOU AN ADVENTURER?": "你是冒险家吗？",
    "at any point to become any available profession. This ability is lost when a profession is chosen.": "在任何时候成为任何可用的职业。选择职业时，此能力会丢失。",
    "Average Health,": "平均健康，",
    "Below Average Charm": "低于平均水平的魅力",
    "Below Average Finesse": "低于平均水平",
    "Below Average Health": "低于平均水平",
    "Below Average Resilience": "低于平均弹性",
    "Below Average Strength": "低于平均强度",
    "Besiegement": "围攻",
    "Boundless Potential": "无限潜力",
    "Brute": "蛮横的",
    "Can be used once per rest to boost all stats for a short duration.": "每次休息可以使用一次，以在短时间内提高所有统计数据。",
    "Cartographer": "制图师",
    "Cat Person": "猫人",
    "CAT WHISPERER": "猫语者",
    "Causes fatigue to build half as quickly": "使疲劳的产生速度减半",
    "Champion": "冠军",
    "class name": "班级名称",
    "Collier": "科利尔",
    "Comedian": "喜剧演员",
    "Commander": "指挥官",
    "Condition": "健康）状况",
    "Covert": "隐蔽",
    "Dash to Adventurer": "冲向冒险家",
    "Decreases damage taken from animals": "减少从动物身上受到的伤害",
    "Defuser": "拆弹器",
    "DESCRIPTION": "描述",
    "Desired Class Name": "所需的类名",
    "Diplomat": "外交官",
    "Dogged March": "顽强的三月",
    "Fabricator": "制造商",
    "Factions & Titles": "派系和头衔",
    "Filcher": "菲尔彻",
    "FISHMONGER": "鱼贩",
    "Forgemaster": "锻造大师",
    "Friendly": "友谊赛",
    "GATEKEEPER": "守门人",
    "Get Random Description": "获取随机描述",
    "Gift of Knowledge": "知识的礼物",
    "gityx the Adventurer": "冒险家吉蒂克斯",
    "Good Finesse": "良好的技巧",
    "Good Insight": "良好的洞察力",
    "Good Resilience": "良好的弹性",
    "Grants a bonus to all elemental attunements": "给予所有元素协调加成",
    "GRASSLAND": "草原",
    "HEAD EQUIPMENT": "头部设备",
    "Heroic Feat": "英雄壮举",
    "Increased chance to find rare items": "增加找到稀有物品的机会",
    "Increases ability to assure during conversation": "提高谈话过程中的保证能力",
    "Increases ability to complain during conversation": "提高在谈话中抱怨的能力",
    "Increases ability to compliment during conversation": "提高谈话中赞美的能力",
    "Increases ability to gossip during conversation": "提高谈话中八卦的能力",
    "Increases ability to successfully disarm traps": "提高成功解除陷阱的能力",
    "Increases ability to successfully request items, services, and information from individuals": "提高向个人成功请求项目、服务和信息的能力",
    "Increases ability to successfully steal": "增加成功偷窃的能力",
    "Increases ability to tell jokes during conversation": "提高谈话中讲笑话的能力",
    "Increases ability to threathen during conversation": "提高谈话中的威胁能力",
    "Increases materials gathered from butchering": "增加从屠宰中收集的材料",
    "Increases materials gathered from harvesting": "增加从收获中收集的材料",
    "Increases materials gathered from mining": "增加从采矿中收集的材料",
    "Increases materials gathered from salvaging": "增加从分解中收集的材料",
    "Increases maximum waypoint limit": "增加最大航路点限制",
    "Increases number items acquired from chests": "增加从箱子中获得的物品数量",
    "Increases proficiency at dancing": "提高舞蹈水平",
    "Increases proficiency with musical instruments": "提高对乐器的熟练程度",
    "Increases quality of items acquired from chests": "提高从箱子中获得的物品的质量",
    "Increases speed during world map travel": "在世界地图旅行期间提高速度",
    "Increases success rate while fishing": "钓鱼时增加成功率",
    "Increases the chance to successfully use lockpicks": "增加成功使用开锁器的机会",
    "Increases the quality of items upgraded with toolkits": "提高使用工具包升级的项目的质量",
    "Increases the rate of relationship gains with individuals": "增加与个人的关系获得率",
    "Irritable": "烦躁",
    "is 5 kilometers to the northeast": "在东北 5 公里处",
    "JADE CIRCLE MANUALS": "玉环手册",
    "Knight": "骑士",
    "Learned Spells (0/3)": "学习法术 (0/3)",
    "Legend": "传奇",
    "MAINHAND EQUIPMENT": "主要设备",
    "Mainhand Required": "需要主手",
    "Map of Grassland": "草原地图",
    "Marathoner": "马拉松运动员",
    "Monster Manual": "怪物图鉴",
    "Moonwalker": "月球漫步者",
    "Motivator": "激励者",
    "Musician": "音乐家",
    "No Bonuses": "没有奖励",
    "No Equipment Available": "没有可用的设备",
    "No matches found for 'holding'.": "没有找到“持有”的匹配项。",
    "No matches found for 'inventory'.": "没有找到“库存”的匹配项。",
    "No Spell Slots": "没有拼写槽",
    "OFFHAND EQUIPMENT": "手持设备",
    "Onward!": "向前！",
    "ONWARD!": "向前！",
    "Persuasive": "有说服力的",
    "Pickpocketer": "扒手",
    "Pine Tree": "松树",
    "Please describe yourself, gityx the Adventurer.": "请描述一下你自己，冒险者 gityx。",
    "Plunderer": "掠夺者",
    "Pocket Watcher": "袖珍守望者",
    "Primal": "原始",
    "QUESTS & REPUTATION": "问题与声誉",
    "RAGAMUFFIN": "拉格玛芬",
    "RANK REQUIRED": "需要排名",
    "Reading Trait Manuals allow you to manifest passive abilities with a wide array of effects.": "阅读特质手册可以让你表现出具有多种效果的被动能力。",
    "Recruit": "招募",
    "Reduces the amount of reputation lost when working against a faction": "减少对抗派系时失去的声望",
    "Reduces the amount of stamina used while moving in stealth": "减少隐身移动时消耗的体力",
    "Reduces the material cost of all craftable items": "降低所有可制作物品的材料成本",
    "Right-Click to Inspect": "右键检查",
    "Right-Click to Read": "右键阅读",
    "Runesmith": "符文匠",
    "SCHOLAR": "学者",
    "Scrapper": "刮板",
    "Seaworthy": "适航",
    "Shadowform": "影形",
    "SHARDS REQUIRED": "需要分片",
    "Sightseer": "观光客",
    "Skinner": "斯金纳",
    "SOLDIER": "士兵",
    "Speak to faction tactician to acquire trait manuals": "与派系战术家交谈以获取特性手册",
    "Squire": "乡绅",
    "Stamina": "耐力",
    "STATS": "统计数据",
    "Sticky Fingers": "粘手指",
    "Sycophant": "谄媚者",
    "Target Filter set to SENTIENT.  2 targets are visible out of a possible 5": "目标过滤器设置为 SENTIENT。在可能的 5 个目标中可见 2 个目标",
    "TARGETS (SENTIENT)": "目标（SENTIENT）",
    "Telltale": "告密者",
    "Text": "文本",
    "They look strangely familiar.": "他们看起来出奇的熟悉。",
    "to be a random class. When you die, your score is added to a persisting total which determines what classes you may choose the next time you play. If you wish to make this decision later, Type": "成为一个随机班级。当你死后，你的分数会被添加到一个持续的总分中，这决定了你下次玩时可以选择的类别。如果您希望稍后做出此决定，请键入",
    "to get a random description. Your description may be up to 2,500 characters long, and you may change it at any time.": "得到一个随机的描述。您的描述最长可达 2,500 个字符，您可以随时更改。",
    "to learn more about the different stats. If you know what you're doing and want access to all classes right away, type": "了解有关不同统计数据的更多信息。如果您知道自己在做什么并希望立即访问所有课程，请输入",
    "to see the complete list of classes. Type": "查看完整的课程列表。类型",
    "TOURIST": "游客",
    "Tracked Quests": "追踪任务",
    "TRAIT": "特征",
    "Transcendent Unity": "超越统一",
    "Trekker": "徒步旅行者",
    "UNEMPLOYED": "失业的",
    "View Journal": "查看日志",
    "WILL OF THE WILD MANUALS": "野蛮人的意志",
    "You dash 4 steps to the southeast.": "你向东南方向冲了 4 步。",
    "You dash 6 steps to the southeast.": "你向东南方向冲刺 6 步。",
    "You fail to uncover anything new.": "你没有发现任何新的东西。",
    "You must enter a name. i.e. '/setname Hero McLegend'": "您必须输入名称。例如'/setname 无敌锅巴'",
    "You search the area within 5 steps of you.": "您在 5 步内搜索该区域。",
    "You stop hiding.": "你别躲了。",
    "1. Start New Adventure": "1.开始新的冒险",
    ". It is smaller than you.": ".它比你小。",
    ". It looks very fast. It is smaller than you.": ".它看起来非常快。它比你小。",
    "'s dash was interrupted!": "的冲刺被打断了！",
    "'s move was interrupted!": "的动作被打断了！",
    "(Attack)": "（攻击）",
    "(Harvest)": "（收成）",
    "(Inspect)": "（检查）",
    "(You)": "（你）",
    "[Grabbed by": "[被抢",
    "[Grabbing": "[抢",
    "1 step  to the southeast.": "向东南走1步。",
    "a": "一个",
    "about eight steps to the northwest.  It is  made of a very common material and is in perfect condition. Items can be placed on this.  It is smaller than you.": "向西北约八步。它由一种非常常见的材料制成，状况良好。物品可以放在上面。它比你小。",
    "about eight steps to the southeast.  It looks ready to be harvested.  It is bigger than you.": "向东南约八步。它看起来可以收获了。它比你大。",
    "about six steps to the northeast.  The initials 'T.L.C' are on its collar. It is": "向东北约六步。首字母“T.L.C”在它的衣领上。这是",
    "about six steps to the west.  It looks ready to be harvested.  It is bigger than you.": "向西大约六步。它看起来可以收获了。它比你大。",
    "about ten steps to the southwest.  The initials 'T.L.C' are on its collar. It is Moving Southwest,": "向西南约十步。首字母“T.L.C”在它的衣领上。它正在向西南移动，",
    "Approach Pine Tree": "接近松树",
    "Approach Pine Tree Seeds": "接近松树种子",
    "Approach Stick": "接近棒",
    "Approach Wooden Log": "接近木原木",
    "Approach Young Pig": "接近小猪",
    "Attack": "攻击",
    "Attack Pine Tree": "攻击松树",
    "Attack Young Pig": "攻击小猪",
    "breaks away from  you!": "离你而去！",
    "Choke Young Pig": "窒息小猪",
    "Climb Pine Tree": "爬松树",
    "Commoner": "布衣",
    "Dash to Pine Tree": "冲向松树",
    "Dash to Pine Tree Seeds": "冲刺松树种子",
    "Dash to Stick": "短跑坚持",
    "Dash to Wooden Log": "冲刺到木原木",
    "Dash to Young Pig": "冲向小猪",
    "Dashing Northeast,": "冲向东北，",
    "Dashing Southwest,": "冲向西南，",
    "dashs 10 steps to the southwest.": "向西南方向冲出 10 步。",
    "Eat Pine Tree Seeds": "吃松树种子",
    "fails to break  your hold!": "未能打破你的控制！",
    "Filter: wooden log": "过滤器：原木",
    "Grab Young Pig": "抓住小猪",
    "Happy": "快乐的",
    "Harvest": "收成",
    "Harvest Pine Tree": "收获松树",
    "has been destroyed.": "已被摧毁。",
    "has gone missing!": "失踪了！",
    "Heavy Attack Pine Tree": "重击松树",
    "Heavy Attack Young Pig": "重击小猪",
    "Inspect Pine Tree": "检查松树",
    "Inspect Pine Tree Seeds": "检查松树种子",
    "Inspect Plant Fiber": "检查植物纤维",
    "Inspect Stick": "检查棒",
    "Inspect Wooden Log": "检查原木",
    "Inspect Young Pig": "检查幼猪",
    "is  ruined.": "被毁了。",
    "It is  5 steps out of your attack range.": "距离你的攻击范围只有 5 步。",
    "It is  9 steps out of your attack range.": "距离你的攻击范围只有 9 步。",
    "Moving Southeast,": "向东南移动，",
    "Moving Southwest,": "向西南移动，",
    "Pet  Young Pig": "宠物小猪",
    "Pine Tree": "松树",
    "PINE TREE": "松树",
    "Pine Tree Seeds": "松树种子",
    "Pine Tree Seeds": "松树种子",
    "Plant Fiber": "植物纤维",
    "prepares to dash.": "准备冲刺。",
    "Release Young Pig": "释放小猪",
    "Right-Click to Attack": "右键攻击",
    "Right-Click to Harvest": "右键收获",
    "rival": "对手",
    "Ruined": "毁了",
    "Scared": "害怕的",
    "Show Recipes Using Plant Fiber": "显示使用植物纤维的食谱",
    "Show Recipes Using Stick": "使用棒显示食谱",
    "Show Recipes Using Wooden Log": "使用木原木显示食谱",
    "Split Pine Tree Seeds": "分裂松树种子",
    "Stick": "木棍",
    "Struggling,": "挣扎，",
    "Take  Pine Tree Seeds": "采取松树种子",
    "Take  Plant Fiber": "服用植物纤维",
    "Take  Stick": "拿棍子",
    "Take  Wooden Log": "取木原木",
    "The initials 'T.L.C' are on its collar.": "首字母“T.L.C”在它的衣领上。",
    "within reach to the east.  The initials 'T.L.C' are on its collar. It is": "向东伸手可及。首字母“T.L.C”在它的衣领上。这是",
    "within reach to the southeast.  It looks ready to be harvested.  It is bigger than you.": "东南方触手可及。它看起来可以收获了。它比你大。",
    "Wooden Blocks": "木块",
    "Wooden Log": "原木",
    "woodenlog": "原木",
    "You attack a": "你攻击一个",
    "You begin approaching 3": "你开始接近 3",
    "You cannot move any closer to a": "你不能再靠近一个",
    "You choke a": "你窒息了",
    "You climb a": "你爬上一个",
    "You closely inspect a": "你仔细检查一个",
    "You do not recover anything useful.": "你没有恢复任何有用的东西。",
    "You grab a": "你抓住一个",
    "You inspect your": "你检查你的",
    "You know 2 recipes related to the term '": "你知道 2 个与“”相关的食谱",
    "You move 5 steps and stop  next to a": "你移动了 5 步，然后在一个",
    "You move 6 steps and stop  next to a": "你移动了 6 步，然后在一个",
    "You must select a target to inspect. Include a valid object number to inspect inventory items.": "您必须选择要检查的目标。包括有效的对象编号以检查库存项目。",
    "You pet a": "你驯服了一只",
    "You pick up 3": "你捡到 3",
    "You pick up some": "你拿起一些",
    "You prepare to grab a": "你准备抓住一只",
    "You recovered some": "你恢复了一些",
    "You release a": "你释放一个",
    "You slap a": "你打一个",
    "You start harvesting a": "你开始收获一个",
    "You uppercut a": "你上勾拳",
    "You wake up feeling like a million doubloons!": "你醒来感觉就像一百万达布隆！",
    "Young Pig": "小猪",
    "Young Pig": "小猪",
    "YOUNG PIG": "小猪",
    "Your": "您的",
    ", but they are too far away.": ", 但它们离得太远了。",
    "!Burning!": "！燃烧！",
    "about four steps to the northeast.  The initials 'T.L.C' are on its collar. It is Dashing Northeast,": "向东北约四步。首字母“T.L.C”在它的衣领上。是潇洒的东北，",
    "about ten steps to the northeast.  The initials 'T.L.C' are on its collar. It is Dashing Northeast,": "往东北走十步左右。首字母“T.L.C”在它的衣领上。是潇洒的东北，",
    "about ten steps to the northeast.  The initials 'T.L.C' are on its collar. It is Moving Northeast,": "往东北走十步左右。首字母“T.L.C”在它的衣领上。它正在向东北移动，",
    "about ten steps to the southeast.  The initials 'T.L.C' are on its collar. It is": "东南约十步。首字母“T.L.C”在它的衣领上。这是",
    "about three steps to the east.  The initials 'T.L.C' are on its collar. It is Moving East,": "向东大约三步。首字母“T.L.C”在它的衣领上。它正在向东移动，",
    "about three steps to the east.  The initials 'T.L.C' are on its collar. It is Moving Northeast,": "向东大约三步。首字母“T.L.C”在它的衣领上。它正在向东北移动，",
    "Approach Orange Tree": "接近橙树",
    "Dash to Orange Tree": "冲向橘子树",
    "Dashing Southeast,": "奔腾东南，",
    "dashs 6 steps to the northeast.": "向东北方向冲刺 6 步。",
    "Drop Tin Shortsword": "落锡制短剑",
    "Exhausted": "筋疲力尽的",
    "Extinguish": "熄灭",
    "Extinguish Campfire": "熄灭营火",
    "Inspect Orange Tree": "检查橙树",
    "It is  2 steps out of your attack range.": "它在你的攻击范围之外 2 步。",
    "It is  3 steps out of your attack range.": "它在你的攻击范围之外 3 步。",
    "Moving East,": "东移，",
    "Moving North,": "向北移动，",
    "Moving Northeast,": "搬到东北，",
    "Orange Tree": "橘子树",
    "Right-Click to Extinguish": "右键熄灭",
    "Right-Click to Take": "右键点击采取",
    "Rune of Earth": "大地符文",
    "Rune of Earth": "大地符文",
    "Salvage Tin Shortsword": "分解锡制短剑",
    "Stow Tin Shortsword": "收起锡制短剑",
    "Swimming": "游泳",
    "Take  Tin Shortsword": "拿起锡制短剑",
    "Throw Tin Shortsword": "扔掉锡制短剑",
    "TIN SHORTSWORD": "锡制短剑",
    "Wear Tin Shortsword": "装备锡制短剑",
    "Wet": "潮湿",
    "You are too Exhausted to dash.": "你太累了，无法冲刺。",
    "You are too tired to grab anything.": "你太累了，抓不到任何东西。",
    "You dash 6 steps to the northeast.": "你向东北冲了 6 步。",
    "You dry off.": "你擦干。",
    "You extinguish a": "你熄灭一个",
    "You light a": "你点亮一个",
    "You move 6 steps  to the location of a": "你移动 6 步到一个位置",
    "You recovered a": "你恢复了一个",
    "You start salvaging a": "你开始挽救一个",
    "You stow your": "你收起你的",
    "You try grabbing a": "你试着抓住一个",
    ", and  the": ", 和",
    ", but they break away!": "，但他们挣脱了！",
    ", some": "， 一些",
    ", the": "， ",
    "!Revealed!": "！揭晓！",
    "\"Relica is particularly special for being the safest known point in the realm.": "“Relica 特别特别，因为它是该领域已知的最安全的地点。",
    "\"Welcome back to Relica!  There is still so much left to do! We still need to put the finishing touches on the": "“欢迎回到 Relica！还有很多事情要做！我们还需要对",
    "(Elder)": "（长老）",
    "[TRACKED]": "[追踪]",
    "1. Journey 20 km south to Last known location of Sheylinn Silvertaker.": "1. 向南行驶 20 公里，到达 Sheylinn Silvertaker 的最后已知位置。",
    "1. Journey 5 km northeast to Relica.": "1. 向东北行驶 5 公里到达 遗迹。",
    "1. RESEARCH PHIPS": "1. 研究成果",
    "2. Cancel": "2. 取消",
    "2. KILL SHEYLINN SILVERTAKER": "2.杀死 Sheylinn SILVERTAKER",
    "3. SLAY A": "3. 杀死",
    "about two steps to the north.  They have very short, braided, auburn hair and enchanting hazel eyes. They are rather tall.  They appear to be a Demon Slayer.  They are  wearing a": "向北大约两步。他们的头发很短，编成辫子，赤褐色的头发和迷人的淡褐色眼睛。他们相当高。他们似乎是恶魔杀手。他们穿着一",
    "Amateur Guard": "业余后卫",
    "An Elder says...": "一位长老说……",
    "Approach Elder": "接近长老",
    "Approach Elder Siegbert": "接近西格伯特长老",
    "Assist": "协助",
    "Assist Elder Siegbert": "协助西格伯特长老",
    "Attack Elder Siegbert": "攻击西格伯特长老",
    "Battle Chest": "战斗宝箱",
    "Big Chest": "大胸",
    "Change Equipment": "更换设备",
    "CONFIRM FAST TRAVEL": "确认快速旅行",
    "CONFIRM GRAB": "确认抓取",
    "Dash to Elder": "冲向长者",
    "Dash to Elder Siegbert": "冲向西格伯特长老",
    "Destroy Pine Tree Seeds": "摧毁松树种子",
    "Destroy Plant Fiber": "破坏植物纤维",
    "Destroy Sticks": "销毁木棍",
    "Destroy Wooden Log": "销毁原木",
    "Do you want to attack Elder Siegbert?": "你想攻击西格伯特长老吗？",
    "Drop Pine Tree Seeds": "掉落松树种子",
    "Drop Plant Fiber": "滴植物纤维",
    "Drop Sticks": "滴棒",
    "Drop Wooden Log": "掉落原木",
    "Earth": "地球",
    "Elder": "长老",
    "Elder Siegbert": "西格伯特长老",
    "Elder Siegbert": "西格伯特长老",
    "Elder Siegbert says...": "西格伯特长老说……",
    "End the life of Sheylinn Silvertaker. Their heinous misdeeds are beyond redemption, and they must be stopped! You have been informed of their last known whereabouts.": "结束 Sheylinn Silvertaker 的生命。他们的罪恶行径已经无可救药，必须予以制止！你已被告知他们最后的下落。",
    "Engaging them in combat would surely be your undoing.": "让他们参与战斗肯定是你的失败。",
    "Explore Grassland": "探索草原",
    "Explore Landmark": "探索地标",
    "Explore Relica": "探索遗迹",
    "Find and inspect a Phip.": "查找并检查 Phip。",
    "Ghostweave Belt of Fire": "鬼纹火焰腰带",
    "Ghostweave Boots of Earth": "鬼纹大地之靴",
    "Ghostweave Cap of Light": "鬼纹光之帽",
    "Ghostweave Gloves of Water": "鬼纹水手套",
    "Ghostweave Tights of Water": "水鬼纹紧身衣",
    "Give  Pine Tree Seeds to": "将松树种子送给",
    "Give  Plant Fiber to": "给植物纤维",
    "Give  Stick to": "坚持",
    "Give  Tin Shortsword to": "给锡制短剑给",
    "Give  Wooden Log to": "将木原木交给",
    "Grab Elder": "抓住长老",
    "Grab Elder Siegbert": "抓住西格伯特长老",
    "Greet Elder": "问候长老",
    "Hold Pine Tree Seeds": "持有松树种子",
    "Hold Plant Fiber": "持有植物纤维",
    "Hold Sticks": "拿着棍子",
    "Hold Tin Shortsword": "拿着锡制短剑",
    "Hold Wooden Log": "拿着木原木",
    "Inspect Elder": "检查长老",
    "Inspect Elder Siegbert": "检查西格伯特长老",
    "Inspect Sticks": "检查棒",
    "Kill Sheylinn Silvertaker": "杀死希林夺银者",
    "Let me go!": "让我走！",
    "looks toward the south.": "看向南方。",
    "NEARBY LANDMARKS": "附近的地标",
    "No landmarks in sight": "看不到地标",
    "obelisk": "方尖碑",
    "PINE TREE SEEDS": "松树种子",
    "PLANT FIBER": "植物纤维",
    "refinery": "炼油厂",
    "Research Phips": "研究论文",
    "Reward:": "报酬：",
    "Right-Click to Assist": "右击辅助",
    "Right-Click to Use": "右键使用",
    "says, \"": "说，\"",
    "Show Recipes Using Sticks": "使用棍子显示食谱",
    "Slay a": "杀死一个",
    "stables": "马厩",
    "Steal from Elder Siegbert": "从西格伯特长老那里偷东西",
    "STICKS": "棍子",
    "Stout Clailm": "粗壮的索赔",
    "Stout Clailm": "粗壮的索赔",
    "STOUT CLAILM": "粗壮的索赔",
    "TASK ACCEPTED:": "接受的任务：",
    "tavern": "酒馆",
    "That said, there are many spectacular things out there for the fearless among us...\"": "也就是说，对于我们中间的无所畏惧的人来说，那里有许多壮观的事情......\”",
    "The further one travels from Relica, the more dangerous things tend to be.": "离雷利卡越远，事情就越危险。",
    "These tiny stones are used to imbue an object with the power of earth. Heavy attacks with earth-infused items inflict poison which deals damage over t...": "这些小石头被用来给物体灌输大地的力量。使用灌土物品的重击会造成毒药，在 t...",
    "They are  1 step out of your attack range.": "他们离你的攻击范围只有1步。",
    "They have very short, braided, auburn hair and enchanting hazel eyes. They are rather tall.": "他们的头发很短，编成辫子，赤褐色的头发和迷人的淡褐色眼睛。他们相当高。",
    "to close this window.": "关闭此窗口。",
    "to make a selection. Press": "进行选择。按",
    "Track and slay a Stout Clailm that is terrorizing the area. Its tracks can be found somewhere near Relica.": "追踪并杀死正在恐吓该地区的粗壮声称。它的踪迹可以在 Relica 附近的某个地方找到。",
    "Travel to Last known location of Sheylinn Silvertaker": "前往 Sheylinn Silvertaker 的最后已知位置",
    "Travel to Recent sighting of a Phip": "前往最近发现的 Phip",
    "warehouse": "仓库",
    "Well": "出色地",
    "Will of the Wild faction. They lead the settlement of Relica.": "野性意志派系。他们领导着 Relica 的定居点。",
    "WOODEN LOG": "木原木",
    "You are already tracking the quest 'Research Phips'.": "您已经在跟踪任务“Research Phips”。",
    "You arrive at Relica.": "你到达了Relica。",
    "You begin exploring the area.": "您开始探索该地区。",
    "You begin your journey to Relica...": "您开始了前往 Relica 的旅程……",
    "You dash was obstructed by": "你冲刺被挡住了",
    "You inspect": "你检查",
    "You leave the area.": "你离开这个区域。",
    "You move  1 step and stop  next to": "你移动 1 步然后停在旁边",
    "You prepare to grab": "你准备抢",
    "You try to grab": "你试图抓住",
    "You wear your": "你穿你的",
    "to": "到",
    "Drop Wooden Breastpl...": "落木胸前...",
    "Give  Wooden Breastplate to": "将木制胸甲交给",
    "Hold Wooden Breastpl...": "装备木制胸甲...",
    "Stow Wooden Breastpl...": "收起木制胸甲",
    "Tin Ingot": "锡锭",
    "WOODEN BREASTPLATE": "木制胸甲",
    "You give your": "你给你的",
    "You have my gratitude.": "我谢谢你嗷。",
    "You learn how to make a Tin Ingot!": "您将学习如何制作锡锭！",
    "You start salvaging your": "你开始挽救你的",
    "'Good morrow.'": "“早上好。”",
    "\"Your tale need not end here, gityx... let your essence bear our blight and you may rise again. Know that the will of fate is never broken, and the icy grip of death grows stronger with every new dawn.\"": "“你的故事不必就此结束，吉蒂克斯……让你的本质承受我们的枯萎，你可能会再次崛起。要知道，命运的意志永远不会破碎，死亡的冰冷魔掌随着每一个新的黎明而变得更加强大。”",
    "*fiercely* attacks  you!": "*猛烈*攻击你！",
    "*fiercely* bodyslams  you!!": "*猛烈地*猛烈抨击你！",
    "*fiercely* roundhouses  you!!": "*猛烈地*让你回旋！！",
    "1. Receive a  blight and attempt resurrection.": "1. 受灾并尝试复活。",
    "A VOICE ECHOES!": "一个声音回响！",
    "Accept your fate and perish.": "接受你的命运，然后灭亡。",
    "As your light begins to fade, something reaches out from the rift.": "当你的光芒开始消退时，有什么东西从裂缝中伸出来。",
    "Assure": "保证",
    "Attacking you,": "攻击你，",
    "attacks  you!": "攻击你！",
    "bites  you!": "咬你！",
    "Blight Received:": "收到的枯萎病：",
    "Chat with  Elder Siegbert": "与西格伯特长老聊天",
    "CHAT WITH ELDER SIEGBERT": "与西格伯特长老聊天",
    "Complain": "投诉",
    "Compliment": "赞扬",
    "Destroy Adventurer": "毁灭冒险家",
    "Dodge  Elder Siegbert": "道奇长老西格伯特",
    "Drop Adventurer": "掉落冒险家",
    "Dying": "垂死",
    "ELDER SIEGBERT": "西格伯特长老",
    "Fiercely Attacking you,": "猛烈攻击你，",
    "gestures.": "手势。",
    "Give  Adventurer to": "给冒险者",
    "Gossip": "闲话",
    "Greet": "迎接",
    "headbutts  you!": "用头撞你！",
    "Heavy Attack": "重击",
    "Heavy Attack Elder Siegbert": "重击西格伯特长老",
    "Hello. You may call me Siegbert Mistscribe.": "你好。你可以叫我 Siegbert Mistscribe。",
    "Hold Adventurer": "持有冒险家",
    "Injured": "受伤",
    "Joke": "玩笑",
    "Map of Relica": "遗迹地图",
    "Moving South,": "南迁，",
    "Normal": "普通的",
    "punches  you!": "揍你！",
    "Reduced Finesse": "降低精细度",
    "shouts, \"": "喊道，\"",
    "Silenced": "沉默",
    "silences  you!": "让你沉默！",
    "Someone else will probably get around to it.": "其他人可能会解决它。",
    "Sometimes it's best to let nature be.": "有时最好顺其自然。",
    "Standard Attack": "标准攻击",
    "Take that!": "拿着它！",
    "TASK ABANDONED": "任务被放弃",
    "They are common sources of clean drinking water.": "它们是清洁饮用水的常见来源。",
    "They have long, kinky, platinum hair and sleepy gray eyes. They are rather short and thin.": "他们有长而卷曲的白金头发和昏昏欲睡的灰色眼睛。它们相当短而薄。",
    "They have short, curly, gray-blue hair and cloudy blue eyes. They are rather short and very fat.": "他们有短而卷曲的灰蓝色头发和混浊的蓝色眼睛。它们很短而且很胖。",
    "They probably aren't THAT bad.": "他们可能没那么糟糕。",
    "Threaten": "威胁",
    "Tin Ingot": "锡锭",
    "uppercuts  you!": "勾搭你！",
    "Wear Adventurer": "穿冒险家",
    "window, or typing": "窗口，或打字",
    "with your": "和你的",
    "within reach to the north.  They have very short, braided, auburn hair and enchanting hazel eyes. They are rather tall.  They appear to be a Demon Slayer.  They are  wearing a": "北边触手可及。他们的头发很短，编成辫子，赤褐色的头发和迷人的淡褐色眼睛。他们相当高。他们似乎是恶魔杀手。他们穿着一",
    "You are dying.": "你快死了。",
    "You are injured.": "你受伤了。",
    "YOU ARE REBORN!": "你重生了！",
    "You are wounded.": "你受伤了。",
    "You attack": "你攻击",
    "You awaken somewhere familiar, your body coarsing with unstable energy...": "你在某个熟悉的地方醒来，你的身体因不稳定的能量而变得粗糙……",
    "You can see all blights affecting you at the bottom of the": "您可以在底部看到所有影响您的疾病",
    "You cannot move any closer to": "你不能再靠近",
    "You closely inspect": "你仔细检查",
    "You greet,": "你打招呼，",
    "You hit": "你打",
    "You smack": "你打",
    "You strike": "你罢工",
    "You take out an": "你拿出一个",
    "Your grab was interrupted!": "你的抓取被打断了！",
    "Blights:": "伤痛：",
    "*critically* headbutts  you!!": "*critically* headbutts  you!!",
    "Amateur Guard": "Amateur Guard",
    "sworn enemy": "死敌",
    "You uppercut": "你上勾拳",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "/status": "/status",
    "/condition": "/condition",
    "'/setclass unemployed'": "'/setclass 失业者'",
    "/classes": "/classes",
    "/define stats": "/define stats",
    "/setclass": "/setclass",
    "/setdesc": "/setdesc",
    "/unlockclasse": "/unlockclasse",
    "/changelog": "/changelog",
    "/clearlocalwaypoint": "/clearlocalwaypoint",
    "/clearwaypoint": "/clearwaypoint",
    "/close": "/close",
    "/craft": "/craft",
    "/goto": "/goto",
    "/help": "/help",
    "/inspect": "/inspect",
    "/makespell": "/makespell",
    "/random": "/random",
    "/recipes": "/recipes",
    "/setlocalwaypoint": "/setlocalwaypoint",
    "/setname": "/setname",
    "/setwaypoint": "/setwaypoint",
    "/stopreports": "/stopreports",
    "/stopsharing": "/stopsharing",
    "/trackwaypoint": "/trackwaypoint",
    "/(number)": "/(number)",
    "": "",
    "": "",
    "": "",
    "\"Welcome to the settlement of Relica! I am Siegbert Mistscribe. We are always in need of foolhardy adventurers to brave the wilds and aid us in making our home the very best. There is still so much left to do! We still need to put the finishing touches on the": "\“欢迎来到遗迹的定居点！我是 西格伯特·米斯特。我们总是需要勇敢的冒险者来勇敢地闯荡荒野，帮助我们把我们的家园变成最好的。还有很多事情要做！我们仍然需要 画龙点睛",
    "You have no hair and hopeless pale eyes. You are unusually short and boney.  You came into this world under squalid conditions in a small uncharted territory far to the south and were raised by a wise couple. In your earlier years, you spent most your time dancing wherever and whenever. One of your most notable memories was the time you saved someone from a wild xeosh. Recently, you have been quick to love others, and are not very social. When faced with obstacles, you often dive in head-first.": "你没有头发和绝望的苍白眼睛。 你异常矮小，骨瘦如柴。 你在肮脏的条件下来到这个世界，在遥远的南方一个未知的小领土上，由一对聪明的夫妇抚养长大。 在你早年，你大部分时间都在随时随地跳舞。 你最显着的记忆之一是你从野蛮的 xeosh 中拯救了一个人。 最近，你很快就爱上了别人，不太善于交际。 遇到障碍时，您通常会一头扎进。",
    "- Scholars gain Enlightenment after conversing with someone or learning a new recipe, temporarily increasing their insight. Scholars can cast spells from scrolls at higher tiers based on their insight, and can use the same scroll several times.": "- 学者在与某人交谈或学习新配方后获得启蒙，暂时增加他们的见识。 学者可以根据他们的洞察力从更高等级的卷轴中施展法术，并且可以多次使用同一个卷轴。",
    "You have very short, kinky, red hair and big pale eyes. You are rather short.  You came from squalid conditions in a tiny hamlet far to the east and were raised by a wise couple. In your earlier years, you spent most your time begging on the street. One of your most notable memories was the time you tried to join the military, but were rejected for being too idealistic. Recently, you have been hesitant to trust others, and are not very loud. When faced with opposition, you often over-complicate things.": "你有一头非常短的、卷曲的、红色的头发和苍白的大眼睛。 你比较矮。 你来自东方遥远的一个小村庄的肮脏条件，由一对聪明的夫妇抚养长大。 在你早年，你大部分时间都在街头乞讨。 你最显着的记忆之一是你试图参军，但因为过于理想主义而被拒绝。 最近，你一直在犹豫是否相信别人，声音也不大。 当面对反对时，你常常把事情复杂化。",
    "You have long, curly, blonde hair and cloudy hazel eyes. You are rather short and lean.  You came from modest conditions in a tiny uncharted territory far to the south and were raised by a very practical community. When you were younger, most of your time was spent learning from thieves. One of your most notable memories was the time you won a poetry contest. Recently, you have been eager to trust others, and are not very timid. When faced with opposition, you often act without hesitation.": "你有一头卷曲的金色长发和朦胧的淡褐色眼睛。 你很矮很瘦。 你来自遥远的南方一个未知的小领土，条件适中，并由一个非常实际的社区抚养长大。 当你年轻的时候，你大部分时间都花在向小偷学习上。 你最显着的记忆之一是你赢得诗歌比赛的那次。 最近，你渴望信任别人，也不是很胆小。 面对反对时，你往往会毫不犹豫地采取行动。",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "W": "W",
    "U": "U",
    "O": "O",
    "S": "S",
    "SE": "SE",
    "E": "E",
    "D": "D",
    "H": "H",
    "A": "A",
    "[Discord]": "[Discord]",
    "SW": "SW",
    "© 2016-2021 @BrianIsCreative": "© 2016-2021 @BrianIsCreative",
    "<": "<",
    ">": ">",
    "the": "",
    "NW": "NW",
    "[@BrianIsCreative]": "[@BrianIsCreative]",
    "NE": "NE",
    "N": "N",
    "G": "G",
    "gityx": "gityx",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Wooden Plank x ": "木板 x ",
    "Wooden Block x ": "木块 x ",
    "(Deletes Save Slot ": "(删除保持插槽 ",
    "You make ": "你制作了 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+). $/,
    /^([\d\.]+)km$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^x ([\d\.,]+)$/,
    /^\[([\d\.,]+)\]$/,
    /^\[([\d\.,]+)x\]$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^What is your profession, (.+)\?$/, '你的职业是什么，$1\?'],
    [/^1. Continue as (.+) the Adventurer$/, '1. 继续使用冒险者 $1'],
    [/^The story of (.+) the Adventurer continues...$/, '冒险者 $1 的故事还在继续……'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You know (.+) recipes.$/, '你知道16个配方。'],
    [/^You dash (.+) steps to the west.$/, '你向西冲了 $1 步。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) day, ([\d\.,]+) hours$/, '$1 天，$2 小时'],
    [/^([\d\.,]+) days, ([\d\.,]+) hours$/, '$1 天，$2 小时'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);